config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls', namespace='users')),
    path('', include('tasks.urls', namespace='tasks')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tasks/urls.py
from django.urls import path

from tasks.apps import TasksConfig
from tasks.views import TaskListView, TaskDetailView, TaskCreateView, TaskUpdateView, TaskDeleteView, StatusCreateView, \
    StatusUpdateView

app_name = TasksConfig.name

urlpatterns = [
    path('tasks/create/', TaskCreateView.as_view(), name='task_create'),
    path('tasks/<int:pk>/update/', TaskUpdateView.as_view(), name='task_update'),
    path('tasks/<int:pk>/', TaskDetailView.as_view(), name='task_detail'),
    path('', TaskListView.as_view(), name='task_list'),
    path('tasks/<int:pk>/delete/', TaskDeleteView.as_view(), name='task_delete'),

    path('tasks/<int:task_pk>/status/create/', StatusCreateView.as_view(), name='status_create'),
    path('tasks/status/<int:pk>/update/', StatusUpdateView.as_view(), name='status_update')
]

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from users.apps import UsersConfig
from users.views import UserCreateView, EmailVerification, UserResetView, UserListView, UserUpdateView, UserDetailView, \
    UserDeleteView

app_name = UsersConfig.name

urlpatterns = [
    path('register/', UserCreateView.as_view(), name='register'),
    path('login/', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('email-confirm/<str:token>/', EmailVerification.as_view(), name='email-confirm'),
    path('password-reset/', UserResetView.as_view(template_name='users/reset_form.html'), name='reset'),

    path('', UserListView.as_view(), name='user_list'),
    path('<int:pk>/update/', UserUpdateView.as_view(), name='user_update'),
    path('<int:pk>/', UserDetailView.as_view(), name='user_detail'),
    path('<int:pk>/delete/', UserDeleteView.as_view(), name='user_delete'),
]

templates/includes/inc_menu.html
<div class="collapse text-bg-dark" id="navbarHeader">
    <div class="container">
        <div class="row">
            <div class="col-sm-8 col-md-7 py-4">
                <h4>About</h4>
                <p class="text-body-secondary">Прототип сайта трекера задач</p>
                <p class="text-body-secondary">На платформе доступна регистрация, управление личным кабинетом, удаление аккаунта.</p>
                <p class="text-body-secondary">Авторизированные пользователи могут создавать задачи. Свои задачи можно просматривать, редактировать и удалять.</p>
            </div>
            <div class="col-sm-4 offset-md-1 py-4">
                <h4>Навигация</h4>
                <ul class="list-unstyled">
                    <li><a href="{% url 'tasks:task_list' %}" class="text-white">Главная</a></li>
                    <li><a href="{% url 'users:user_list' %}" class="text-white">Участники</a></li>
                    {% if user.is_authenticated %}
                    <li><a href="{% url 'users:user_detail' user.pk %}" class="text-white">Личный аккаунт</a></li>
                    <li>
                    <form action="{% url 'users:logout' %}" class="row" method="post">
                        {% csrf_token %}
                        <input type="submit" class="text-white" value="Выход">
                    </form>
                    </li>
                    {% else %}
                        <li><a href="{% url 'users:login' %}" class="text-white">Вход</a></li>
                        <li><a href="{% url 'users:register' %}" class="text-white">Регистрация</a></li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </div>
</div>
<div class="navbar navbar-dark bg-dark shadow-sm">
    <div class="container">
        <a href="#" class="navbar-brand d-flex align-items-center">
            <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="none" stroke="currentColor"
                 stroke-linecap="round" stroke-linejoin="round" stroke-width="2" aria-hidden="true" class="me-2"
                 viewBox="0 0 24 24">
                <path d="M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z"/>
                <circle cx="12" cy="13" r="4"/>
            </svg>
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarHeader"
                aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
    </div>
</div>