config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls', namespace='users')),
    path('', include('tasks.urls', namespace='tasks')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tasks/urls.py
from django.urls import path

from tasks.apps import TasksConfig
from tasks.views import TaskListView, TaskDetailView, TaskCreateView, TaskUpdateView, TaskDeleteView, StatusCreateView, \
    StatusUpdateView

app_name = TasksConfig.name

urlpatterns = [
    path('tasks/create/', TaskCreateView.as_view(), name='task_create'),
    path('tasks/<int:pk>/update/', TaskUpdateView.as_view(), name='task_update'),
    path('tasks/<int:pk>/', TaskDetailView.as_view(), name='task_detail'),
    path('', TaskListView.as_view(), name='task_list'),
    path('tasks/<int:pk>/delete/', TaskDeleteView.as_view(), name='task_delete'),

    path('tasks/<int:task_pk>/status/create/', StatusCreateView.as_view(), name='status_create'),
    path('tasks/status/<int:pk>/update/', StatusUpdateView.as_view(), name='status_update')
]

tasks/models.py
from datetime import timedelta

from django.db import models

from users.models import User

NULLABLE = {'blank': True, 'null': True}


class Task(models.Model):
    title = models.CharField(
        max_length=100,
        verbose_name='Название задачи',
        help_text='Укажите название задачи',
    )
    description = models.TextField(
        verbose_name='Текст задачи',
        help_text='Добавьте текст задачи',
        **NULLABLE
    )
    image = models.ImageField(
        upload_to='tasks/images',
        verbose_name='Изображение',
        help_text='Загрузите изображение для задачи, если это необходимо',
        **NULLABLE
    )
    file = models.FileField(
        upload_to='tasks/files',
        verbose_name='Файл',
        help_text='Загрузите файл для задачи, если это необходимо',
        **NULLABLE
    )
    presumable_completion_time = models.DurationField(
        default=timedelta(hours=5),
        verbose_name='Предполагаемое время выполнения',
        help_text='Укажите предполагаемое время выполнения задачи',
        **NULLABLE
    )

    class Meta:
        verbose_name = 'Задача'
        verbose_name_plural = 'Задачи'

    def __str__(self):
        return self.title


class StatusTypeChoices(models.TextChoices):
    """Status type choices"""
    CREATED = 'Задача создана'
    ASSIGNED = 'Назначен исполнитель'
    COMPLETED = 'Задача выполнена'
    REVIEWED = 'Задача проверена'


class Status(models.Model):
    """Status database model"""
    task = models.ForeignKey(
        Task,
        on_delete=models.CASCADE,
        related_name='statuses'
    )
    type = models.CharField(
        max_length=20,
        choices=StatusTypeChoices,
        verbose_name='Тип статуса'
    )
    person_in_charge = models.ForeignKey(
        User,
        on_delete=models.SET_NULL,
        related_name='statuses',
        verbose_name='Ответственное лицо',
        **NULLABLE
    )
    created_at = models.DateTimeField(
        auto_now_add=True,
        verbose_name='Дата создания статуса',
    )

    class Meta:
        verbose_name = 'Статус'
        verbose_name_plural = 'Статусы'
        constraints = (models.UniqueConstraint(fields=['task', 'type'], name='task_type_unique_constraint'),)

    def __str__(self):
        return f'{self.type} - {self.task.title}'

tasks/forms.py
from django.forms import ModelForm, forms, BooleanField, IntegerField

from tasks.models import Task, Status


class StyleFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if isinstance(field, BooleanField):
                field.widget.attrs['class'] = 'form-check-input'
            else:
                field.widget.attrs['class'] = 'form-control'


class TaskForm(StyleFormMixin, ModelForm):
    class Meta:
        model = Task
        fields = ('title', 'description', 'image', 'file', 'presumable_completion_time')

    @staticmethod
    def check_restrictions(field, field_name):
        restrictions = ['казино', 'криптовалюта', 'крипта', 'биржа', 'дешево',
                        'бесплатно', 'обман', 'полиция', 'радар']  # Запрещенные слова
        for word in restrictions:
            if word in field:
                raise forms.ValidationError(f"В поле {field_name} присутствует запрещенное слово: {word}")

    def clean_title(self):
        name = self.cleaned_data.get('title')
        self.check_restrictions(name, 'title')

        return name

    def clean_description(self):
        description = self.cleaned_data.get('description')
        self.check_restrictions(description, 'description')

        return description


class StatusForm(StyleFormMixin, ModelForm):
    class Meta:
        model = Status
        fields = ('person_in_charge',)

tasks/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect, Http404
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView

from tasks.forms import StatusForm
from tasks.models import Task, Status, StatusTypeChoices


class TaskListView(LoginRequiredMixin, ListView):
    model = Task

    def get_queryset(self):
        return self.model.objects.prefetch_related('statuses').all()


class TaskDetailView(LoginRequiredMixin, DetailView):
    model = Task
    def get_queryset(self):
        return self.model.objects.prefetch_related('statuses').all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        statuses = self.object.statuses.order_by('created_at').all()
        context['forms'] =  [StatusForm(instance=status) for status in statuses]
        context['types'] = StatusTypeChoices
        if len(statuses) < 4:
            context['empty_form'] = StatusForm()
            last = context['forms'][-1].instance
            if last.type == StatusTypeChoices.CREATED:
                context['empty_form_title'] = 'Назначить исполнителя'
            elif last.type == StatusTypeChoices.ASSIGNED:
                context['empty_form_title'] = 'Подтвердить выполнение'
            elif last.type == StatusTypeChoices.COMPLETED:
                context['empty_form_title'] = 'Одобрить решение'
        return context


class TaskCreateView(LoginRequiredMixin, CreateView):
    model = Task
    fields = ('title', 'description', 'image', 'file')
    success_url = reverse_lazy('tasks:task_list')
    def form_valid(self, form):
        self.object = form.save()
        Status.objects.create(task=self.object, type=StatusTypeChoices.CREATED, person_in_charge=self.request.user)
        return HttpResponseRedirect(self.get_success_url())


class TaskUpdateView(LoginRequiredMixin, UpdateView):
    model = Task
    fields = ('title', 'description', 'image', 'file')

    def get_success_url(self):
        return reverse('tasks:task_detail', kwargs={'pk': self.object.pk})


class TaskDeleteView(LoginRequiredMixin, DeleteView):
    model = Task
    success_url = reverse_lazy('tasks:task_list')


class StatusCreateView(LoginRequiredMixin, CreateView):
    model = Status
    form_class = StatusForm

    def get_success_url(self):
        return reverse('tasks:task_detail', kwargs={'pk': self.object.task.pk})

    def form_valid(self, form):
        task_pk = self.kwargs.get('task_pk', '')
        try:
            task = Task.objects.get(pk=task_pk)
        except Task.DoesNotExists:
            raise Http404
        self.object = form.save(commit=False)
        self.object.task = task
        newest_status = task.statuses.order_by('created_at').last()
        if newest_status.type == StatusTypeChoices.CREATED:
            self.object.type = StatusTypeChoices.ASSIGNED
        elif newest_status.type == StatusTypeChoices.ASSIGNED:
            self.object.type = StatusTypeChoices.COMPLETED
        else:
            self.object.type = StatusTypeChoices.REVIEWED
        self.object.save()
        return HttpResponseRedirect(self.get_success_url())


class StatusUpdateView(LoginRequiredMixin, UpdateView):
    model = Status
    form_class = StatusForm

    def get_success_url(self):
        return reverse('tasks:task_detail', kwargs={'pk': self.object.task.pk})

tasks/templates/tasks/task_confirm_delete.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-6">
            <form class="row" method="post" enctype="multipart/form-data">
                <div class="card">
                    <p class="card-text">Действительно хотите удалить задачу {{ object.title }}?</p>
                    <div class="card-body">
                        {% csrf_token %}
                    </div>
                    <button type="submit" class="btn btn-primary">
                        Удалить
                    </button>
                    <a class="btn btn-primary" href="{% url 'tasks:task_list'%}" role="button">Отмена</a>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

tasks/templates/tasks/task_detail.html
{% extends 'base.html' %}
{% load my_tags %}
{% block content %}
<div class="album py-5 bg-body-tertiary">
    <div class="container">
        <div  class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
            <div style="height: 25rem;" class="col-6">
                <div class="card shadow-sm">
                    <p class="card-text"><strong>{{ task.title }} - {{ task.presumable_completion_time }}</strong></p>
                    <div style="height: 20rem;" class="card-body">

                        <div class="card-text">{{ task.description }}</div>
                        <p class="card-text">{{ task.file }}</p>
                        <div class="d-flex justify-content-between align-items-center">
                            <div class="btn-group">
                                <a class="btn btn-primary" href="{% url 'tasks:task_list'%}" role="button">Назад</a>
                                <a class="btn btn-primary" href="{% url 'tasks:task_update' task.pk %}" role="button">Редактировать</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div  class="col-6">

                    {% if task.image %}
                        <img style="height: 25rem;" src="{{ task.image | media_filter }}">
                    {% endif %}

            </div>
                    </div>
                    <div class="row g-3 mt-3">
                        {% for form in forms %}
                        <div class="col-3">
                            <div class="card shadow-sm">
                                <div class="card-body">
                                    <form method="post" action="{% url 'tasks:status_update' form.instance.pk %}">
                                        {{ form.instance.type }}
                                        {% csrf_token %}
                                        {{ form.as_p }}
                                        <input type="submit" value="Назначить"/>
                                    </form>
                                </div>
                            </div>
                        </div>
                        {% endfor %}
                        {% if empty_form %}
                        <div class="col-3">
                            <div class="card shadow-sm">
                                <div class="card-body">
                                    <p class="card-text">{{ empty_form_title }}</p>
                                    <form method="post" action="{% url 'tasks:status_create' task.pk %}">
                                        {{ empty_form.instance.type }}
                                        {% csrf_token %}
                                        {{ empty_form.as_p }}
                                        <input type="submit" value="Назначить"/>
                                    </form>
                                </div>
                            </div>
                        </div>
                        {% endif %}


                    </div>
                </div>
            </div>
            {% endblock %}

tasks/templates/tasks/task_form.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-6">
            <form class="row" method="post" enctype="multipart/form-data">
                <div class="card">
                    <div class="card-body">
                        {% csrf_token %}
                        {{ form.as_p }}
                    </div>
                    <button type="submit" class="btn btn-primary">
                        {% if object %}
                        Сохранить
                        {% else %}
                        Создать
                        {% endif %}
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

tasks/templates/tasks/task_list.html
{% extends 'base.html' %}
{% load my_tags %}
{% block content %}
<div class="album py-5 bg-body-tertiary">
    <div class="container">

        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
            {% for task in object_list %}
            <div class="col">
                <div class="card shadow-sm">
                    <div class="card-body">
                        <p class="card-text"><strong>{{ task.title }} - {{ task.presumable_completion_time }}</strong></p>
                        <p class="card-text">{{ task.description | truncatechars:100 }}</p>
                        <div class="d-flex justify-content-between align-items-center">
                            <div class="btn-group">
                                <a class="btn btn-primary" href="{% url 'tasks:task_detail' task.pk %}" role="button">Посмотреть</a>
                                <a class="btn btn-primary" href="{% url 'tasks:task_update' task.pk %}" role="button">Редактировать</a>
                                <a class="btn btn-primary" href="{% url 'tasks:task_delete' task.pk %}" role="button">Удалить</a>
                            </div>

                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>

    </div>
</div>
{% endblock %}