config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls', namespace='users')),
    path('', include('tasks.urls', namespace='tasks')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tasks/urls.py
from django.urls import path

from tasks.apps import TasksConfig
from tasks.views import TaskListView, TaskDetailView, TaskCreateView, TaskUpdateView, TaskDeleteView, StatusCreateView, \
    StatusUpdateView

app_name = TasksConfig.name

urlpatterns = [
    path('tasks/create/', TaskCreateView.as_view(), name='task_create'),
    path('tasks/<int:pk>/update/', TaskUpdateView.as_view(), name='task_update'),
    path('tasks/<int:pk>/', TaskDetailView.as_view(), name='task_detail'),
    path('', TaskListView.as_view(), name='task_list'),
    path('tasks/<int:pk>/delete/', TaskDeleteView.as_view(), name='task_delete'),

    path('tasks/<int:task_pk>/status/create/', StatusCreateView.as_view(), name='status_create'),
    path('tasks/status/<int:pk>/update/', StatusUpdateView.as_view(), name='status_update')
]

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from users.apps import UsersConfig
from users.views import UserCreateView, EmailVerification, UserResetView, UserListView, UserUpdateView, UserDetailView, \
    UserDeleteView

app_name = UsersConfig.name

urlpatterns = [
    path('register/', UserCreateView.as_view(), name='register'),
    path('login/', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('email-confirm/<str:token>/', EmailVerification.as_view(), name='email-confirm'),
    path('password-reset/', UserResetView.as_view(template_name='users/reset_form.html'), name='reset'),

    path('', UserListView.as_view(), name='user_list'),
    path('<int:pk>/update/', UserUpdateView.as_view(), name='user_update'),
    path('<int:pk>/', UserDetailView.as_view(), name='user_detail'),
    path('<int:pk>/delete/', UserDeleteView.as_view(), name='user_delete'),
]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django_countries.fields import CountryField
from phonenumber_field.modelfields import PhoneNumberField

NULLABLE = {'blank': True, 'null': True}


class User(AbstractUser):
    """User model"""
    username = None
    email = models.EmailField(
        unique=True,
        verbose_name='email address'
    )
    name = models.CharField(
        max_length=100,
        verbose_name='Имя',
        help_text='Укажите имя',
        **NULLABLE
    )
    lastname = models.CharField(
        max_length=100,
        verbose_name='Фамилия',
        help_text='Укажите фамилию',
        **NULLABLE
    )
    phone = PhoneNumberField(
        verbose_name='Номер телефона',
        help_text='Введите номер телефона',
        **NULLABLE
    )
    country = CountryField(
        verbose_name='Страна',
        help_text='Выберите страну',
        **NULLABLE
    )
    avatar = models.ImageField(
        upload_to='users/avatars/',
        verbose_name='Аватар',
        help_text='Загрузите аватар',
        **NULLABLE
    )
    token = models.CharField(
        max_length=100,
        verbose_name='Токен',
        blank=True, null=True,
        help_text='Токен для входа в систему'
    )

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    class Meta:
        verbose_name = 'Пользователь'
        verbose_name_plural = 'Пользователи'
        ordering = ['-id']

    def __str__(self):
        return self.email

users/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.forms import Form, EmailField, ValidationError, BooleanField, ModelForm

from users.models import User


class StyleFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if isinstance(field, BooleanField):
                field.widget.attrs['class'] = 'form-check-input'
            else:
                field.widget.attrs['class'] = 'form-control'


class UserRegisterForm(StyleFormMixin, UserCreationForm):
    class Meta:
        model = User
        fields = ('email', 'password1', 'password2')


class UserResetForm(StyleFormMixin, Form):
    email = EmailField()

    def clean_email(self):
        email = self.cleaned_data.get('email')
        qs = User.objects.filter(email=email)
        if not qs.exists():
            raise ValidationError('Пользователь с таким email не найден')
        self.user = qs.first()
        return email

class UserForm(StyleFormMixin, ModelForm):
    class Meta:
        model = User
        fields = ('name', 'lastname', 'avatar', 'country', 'phone')

users/views.py
import secrets

from django.conf import settings
from django.contrib.auth.hashers import make_password
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.mail import send_mail
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404
from django.urls import reverse_lazy, reverse
from django.views import View
from django.views.generic import CreateView, FormView, ListView, DetailView, UpdateView, DeleteView

from users.forms import UserRegisterForm, UserResetForm, UserForm
from users.models import User
from users.services import send_verification_mail


class UserCreateView(CreateView):
    """
    View for registering new users.
    """
    model = User
    form_class = UserRegisterForm
    success_url = reverse_lazy('users:login')

    def form_valid(self, form):
        user = form.save(commit=False)
        user.is_active = False
        user.save()
        token = secrets.token_hex(16)
        user.token = token
        host = settings.MAIN_HOST
        send_verification_mail(host, user.email, token)
        return super().form_valid(form)


class EmailVerification(View):
    def get(self, request, *args, **kwargs):
        user = get_object_or_404(User, token=self.kwargs.get('token', ''))
        user.is_active = True
        user.save()
        return HttpResponseRedirect(reverse('users:login'))


class UserResetView(FormView):
    form_class = UserResetForm
    success_url = reverse_lazy('users:login')

    def form_valid(self, form):
        user = form.user
        password = self.generate_password()
        user.password = make_password(password)
        user.save()

        send_mail(
            subject='Сброс пароля',
            message=f'Ваш новый пароль: {password}',
            from_email=settings.EMAIL_HOST_USER,
            recipient_list=[user.email],
        )
        return super().form_valid(form)

    @staticmethod
    def generate_password():
        return secrets.token_hex(5)


class UserListView(ListView):
    model = User


class UserDetailView(DetailView):
    model = User


class UserUpdateView(LoginRequiredMixin, UpdateView):
    model = User
    form_class = UserForm

    def get_success_url(self):
        return reverse('users:user_detail', kwargs={'pk': self.object.pk})


class UserDeleteView(LoginRequiredMixin, DeleteView):
    model = User
    success_url = reverse_lazy('users:user_list')

users/templates/users/login.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <form class="row" method="post" enctype="multipart/form-data">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    {% csrf_token %}
                    {{ form.as_p }}
                </div>
                <button type="submit" class="btn btn-primary">
                    Войти
                </button>
                <a href="{% url 'users:reset' %}">Восстановить пароль</a>
            </div>
        </div>
    </form>
</div>
{% endblock %}

users/templates/users/reset_form.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <form class="row" method="post" enctype="multipart/form-data">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    {% csrf_token %}
                    {{ form.as_p }}
                </div>
                <button type="submit" class="btn btn-primary">
                    Сбросить пароль
                </button>
            </div>
        </div>
    </form>
</div>
{% endblock %}

users/templates/users/user_confirm_delete.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-6">
            <form class="row" method="post" enctype="multipart/form-data">
                <div class="card">
                    <p class="card-text">Действительно хотите удалить {{ object.email }}?</p>
                    <div class="card-body">
                        {% csrf_token %}
                    </div>
                    <button type="submit" class="btn btn-primary">
                        Удалить
                    </button>
                    <a class="btn btn-primary" href="{% url 'users:user_list'%}" role="button">Отмена</a>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

users/templates/users/user_detail.html
{% extends 'base.html' %}
{% load my_tags %}
{% block content %}
<div class="album py-5 bg-body-tertiary">
    <div class="container">

        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
            <div class="col">
                <div class="card shadow-sm">
                    <img style="height: 20rem;" src="{{ user.avatar | media_filter }}">
                    <div class="card-body">
                        <p class="card-text">{{ user.name }} {{ user.lastname }}</p>
                        <p class="card-text">Почта: {{ user.email }}</p>
                        <p class="card-text">Телефон: {{ user.phone }}</p>
                        <p class="card-text">Страна: {{ user.country }}</p>
                        <div class="d-flex justify-content-between align-items-center">
                            <div class="btn-group">
                                <a class="btn btn-primary" href="{% url 'users:user_list'%}" role="button">Назад</a>
                                <a class="btn btn-primary" href="{% url 'users:user_update' user.pk %}" role="button">Редактировать</a>
                                <a class="btn btn-primary" href="{% url 'users:user_delete' user.pk %}"
                                   role="button">Удалить</a>
                            </div>
                            <br>
                            <div>
                                <small class="text-body-secondary">Присоединился: {{ user.date_joined }}</small>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>
</div>
{% endblock %}

users/templates/users/user_form.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-6">
            <form class="row" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="card">
                    <div class="card-body">

                        {{ form.as_p }}
                    </div>
                    <button type="submit" class="btn btn-primary">
                        {% if object %}
                        Сохранить
                        {% else %}
                        Зарегистрироваться
                        {% endif %}
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

users/templates/users/user_list.html
{% extends 'base.html' %}
{% load my_tags %}
{% block content %}
<div class="album py-5 bg-body-tertiary">
    <div class="container">

        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
            {% for user in object_list %}
            <div class="col">
                <div class="card shadow-sm">
                    <img style="height: 20rem;" src="{{ user.avatar | media_filter }}">
                    <div class="card-body">
                        <p class="card-text">{{ user.name }} {{ user.lastname }}</p>
                        <p class="card-text">Почта: {{ user.email }}</p>
                        <p class="card-text">Телефон: {{ user.phone }}</p>
                        <p class="card-text">Страна: {{ user.country }}</p>
                        <div class="d-flex justify-content-between align-items-center">
                            <div class="btn-group">
                                <a class="btn btn-primary" href="{% url 'users:user_detail' user.pk %}"
                                   role="button">Посмотреть</a>
                                <a class="btn btn-primary" href="{% url 'users:user_update' user.pk %}"
                                   role="button">Редактировать</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>

    </div>
</div>
{% endblock %}